export default Object.freeze({
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  LOG_OUT: '/log-out',
  MENU: '/menu',
  MENU_ITEM: '/menu/:name/:id',
  ORDER_HISTORY: '/order-history',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PLANNER: '/planner',
  ABOUT: '/about',
  CONTACT: '/contact',
  DELIVERY: '/delivery',
  ACCOUNT: '/account',
});
