const ADD_SUCCESS = 'menu/ADD_SUCCESS';

const FETCH_REQUEST = 'menu/FETCH_REQUEST';
const FETCH_SUCCESS = 'menu/FETCH_SUCCESS';
const FETCH_ERROR = 'menu/FETCH_ERROR';
const FETCH_CATEGORIES = 'categories/FETCH_CATEGORIES';
const FETCH_ITEM_WITH_ID = 'menu/FETCH_ITEM_WITH_ID';

export default {
  ADD_SUCCESS,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  FETCH_CATEGORIES,
  FETCH_ITEM_WITH_ID,
};
